<?php

namespace Drupal\eca_field_widget_actions\Plugin\FieldWidgetAction;

use Drupal\Component\Utility\NestedArray;
use Drupal\Core\Ajax\AjaxResponse;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\StringTranslation\TranslatableMarkup;
use Drupal\eca\Event\TriggerEvent;
use Drupal\eca_field_widget_actions\Event\FieldWidgetEvent;
use Drupal\field_widget_actions\Ajax\FillEditorCommand;
use Drupal\eca_field_widget_actions\Ajax\FillCompoundFieldCommand;
use Drupal\field_widget_actions\Attribute\FieldWidgetAction;
use Drupal\field_widget_actions\FieldWidgetActionBase;
use Symfony\Component\DependencyInjection\ContainerInterface;

/**
 * The field widget action for ECA.
 */
#[FieldWidgetAction(
  id: 'eca_field_widget',
  label: new TranslatableMarkup('ECA Field Widget'),
  widget_types: [],
  field_types: [],
  category: new TranslatableMarkup('ECA Field Widgets'),
  deriver: 'Drupal\eca_field_widget_actions\Plugin\FieldWidgetAction\EcaFieldWidgetDeriver',
)]
class EcaFieldWidget extends FieldWidgetActionBase {

  /**
   * The event dispatcher.
   *
   * @var \Drupal\eca\Event\TriggerEvent
   */
  protected TriggerEvent $triggerEvent;

  /**
   * {@inheritdoc}
   */
  public static function create(ContainerInterface $container, array $configuration, $plugin_id, $plugin_definition) {
    $instance = parent::create($container, $configuration, $plugin_id, $plugin_definition);
    $instance->triggerEvent = $container->get('eca.trigger_event');
    return $instance;
  }

  /**
   * {@inheritdoc}
   */
  public function defaultConfiguration(): array {
    return [
      'direct_fill' => FALSE,
    ] + parent::defaultConfiguration();
  }

  /**
   * {@inheritdoc}
   */
  public function buildConfigurationForm(array $form, FormStateInterface $form_state, $action_id = NULL): array {
    $form = parent::buildConfigurationForm($form, $form_state, $action_id);
    $form['direct_fill'] = [
      '#type' => 'checkbox',
      '#title' => $this->t('Fill the field directly'),
      '#default_value' => $this->configuration['direct_fill'] ?? FALSE,
      '#description' => $this->t('When enabled, the value returned by the ECA model fills the field directly, without showing the suggestions confirmation dialog. Works with all standard widgets including CKEditor. For compound fields (Link, Address), each sub-field is filled directly. Multi-value fields fall back to the suggestions behavior.'),
    ];
    return $form;
  }

  /**
   * {@inheritdoc}
   */
  public function submitConfigurationForm(array &$form, FormStateInterface $form_state): void {
    $this->configuration['direct_fill'] = (bool) $form_state->getValue('direct_fill');
  }

  /**
   * {@inheritdoc}
   */
  public function getAjaxCallback(): ?string {
    return 'executeWidget';
  }

  /**
   * {@inheritdoc}
   */
  public function getLibraries(): array {
    return ['field_widget_actions/commands', 'eca_field_widget_actions/fill_compound_field'];
  }

  /**
   * Ajax handler for ECA field widget.
   */
  public function executeWidget(array &$form, FormStateInterface $form_state): AjaxResponse {
    // The derivative ID is the wildcard generated by FieldWidgetActionsEvent
    // (prefixed with the ECA model ID to prevent collisions between models
    // that share event IDs - e.g. after cloning). See issue #3588904.
    $id = $this->getDerivativeId();
    $fieldKey = $this->getTargetElementDelta($form, $form_state);
    $fieldName = $this->getTargetElementFieldName($form, $form_state);
    $selector = $this->getSuggestionsTarget($form, $form_state);
    /** @var \Drupal\Core\Entity\ContentEntityInterface $entity */
    $entity = static::buildEntity($form, $form_state);
    $event = $this->triggerEvent->dispatchFromPlugin('eca_field_widget_actions:eca_field_widget', $id, $entity, $fieldName, $fieldKey);
    $value = $event instanceof FieldWidgetEvent ? $event->getWidgetValue() : NULL;
    if (!empty($this->configuration['direct_fill']) && $value !== NULL && is_scalar($value)) {
      $response = new AjaxResponse();
      $css_selector = '[data-drupal-selector="' . $selector . '"]';
      $response->addCommand(new FillEditorCommand($css_selector, (string) $value));
      return $response;
    }
    if (!empty($this->configuration['direct_fill']) && is_array($value) && !empty($value)) {
      $triggering_element = $form_state->getTriggeringElement();
      $array_parents = $triggering_element['#array_parents'];
      array_pop($array_parents);
      $widget_element = NestedArray::getValue($form, $array_parents) ?? [];
      $sub_selectors = $this->findSubFieldSelectors($widget_element, array_keys($value));
      $wrapper_selector = isset($widget_element['#attributes']['data-drupal-selector'])
        ? '[data-drupal-selector="' . $widget_element['#attributes']['data-drupal-selector'] . '"]'
        : NULL;
      if (!empty($sub_selectors)) {
        $missing_keys = array_diff(array_keys($value), array_keys($sub_selectors));
        // Always use FillCompoundFieldCommand so that resolveFormControl() in
        // JS can unwrap compound elements like address_country whose
        // data-drupal-selector points to a wrapper <div>, not the inner
        // <select>. FillSimpleFieldCommand sets .value directly on the matched
        // element, which silently fails on wrapper divs.
        $immediate = [];
        foreach ($sub_selectors as $key => $sub_selector) {
          $immediate['[data-drupal-selector="' . $sub_selector . '"]'] = (string) $value[$key];
        }
        $deferred = [];
        foreach ($missing_keys as $key) {
          $deferred[$key] = (string) $value[$key];
        }
        $response = new AjaxResponse();
        $response->addCommand(new FillCompoundFieldCommand($immediate, $deferred, $wrapper_selector));
        return $response;
      }
      // No sub-fields found in the form tree yet.  Look for an AJAX-enabled
      // input whose change event triggers a widget rebuild that exposes the
      // missing sub-fields (e.g. the country select in an address widget).
      $trigger = $this->findAjaxTrigger($widget_element);
      if ($trigger !== NULL) {
        // Resolve the trigger value: prefer the ECA-supplied value (most
        // authoritative), then fall back to whatever the form currently shows.
        $trigger_value = (string) ($value[$trigger['key']] ?? $trigger['value']);
        if ($trigger_value !== '') {
          $immediate = ['[data-drupal-selector="' . $trigger['selector'] . '"]' => $trigger_value];
          $deferred = [];
          foreach ($value as $k => $v) {
            if ($k !== $trigger['key']) {
              $deferred[$k] = (string) $v;
            }
          }
          $response = new AjaxResponse();
          $response->addCommand(new FillCompoundFieldCommand($immediate, $deferred, $wrapper_selector));
          return $response;
        }
      }
    }
    return $this->returnSuggestions($value ?? '', $selector);
  }

  /**
   * Depth-first search for the first AJAX-enabled non-button input.
   *
   * Compound widgets like Address have a select (e.g. country) that carries a
   * Drupal #ajax handler — changing it triggers a server-side rebuild that
   * renders the remaining sub-fields.  This method finds that element so its
   * current value can be used as the "immediate" fill that initiates the
   * rebuild, after which all other values are applied as deferred fills.
   *
   * @param array $element
   *   The form subtree to search.
   *
   * @return array|null
   *   Associative array with keys:
   *   - key: the form element key.
   *   - selector: the data-drupal-selector value.
   *   - value: the element's current or default value (string).
   *   Returns NULL if no suitable trigger is found.
   */
  protected function findAjaxTrigger(array $element): ?array {
    foreach ($element as $key => $child) {
      if (str_starts_with((string) $key, '#') || !is_array($child)) {
        continue;
      }
      // Only consider actual form inputs — skip buttons and submits.
      if (isset($child['#ajax']) && !in_array($child['#type'] ?? '', ['button', 'submit', 'image_button'], TRUE)) {
        $selector = $child['#attributes']['data-drupal-selector'] ?? ($child['#id'] ?? NULL);
        if ($selector !== NULL) {
          // #value is '' (not NULL) when nothing was submitted yet, so ?? alone
          // would never fall through to #default_value.
          $v = (string) ($child['#value'] ?? '');
          if ($v === '') {
            $v = (string) ($child['#default_value'] ?? '');
          }
          return ['key' => $key, 'selector' => $selector, 'value' => $v];
        }
      }
      $result = $this->findAjaxTrigger($child);
      if ($result !== NULL) {
        return $result;
      }
    }
    return NULL;
  }

  /**
   * Recursively finds form sub-field selectors matching the given keys.
   *
   * Walks the form element tree depth-first, skipping render API properties.
   * When a child key matches one of $keys, records its data-drupal-selector
   * (or #id as fallback) and stops recursing into that child.
   *
   * @param array $element
   *   The form subtree to search.
   * @param array $keys
   *   The sub-property keys to look for (e.g. ['uri', 'title']).
   *
   * @return array
   *   Map of matched key => selector string.
   */
  protected function findSubFieldSelectors(array $element, array $keys): array {
    $found = [];
    foreach ($element as $key => $child) {
      if (str_starts_with((string) $key, '#') || !is_array($child)) {
        continue;
      }
      if (in_array($key, $keys, TRUE)) {
        $sub_selector = $child['#attributes']['data-drupal-selector'] ?? ($child['#id'] ?? NULL);
        if ($sub_selector !== NULL) {
          $found[$key] = $sub_selector;
        }
        // Do not recurse into a matched element.
        continue;
      }
      $found += $this->findSubFieldSelectors($child, $keys);
    }
    return $found;
  }

}
